server:
  port: 9102
spring:
  zipkin:
    base-url: http://zipkin:9004
    enabled: true
  application:
    name: authorization-service    # 项目名称尽量用小写
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/test_data?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:9000/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
    status-page-url: http://localhost:${server.port}/swagger-ui.html
default:
  defaultRootPassword: root123
  defaultRootUsername: root