server:
  port: 19103
spring:
  zipkin:
    base-url: http://zipkin:19004
    enabled: true
  application:
    name: dict-service    # 项目名称尽量用小写
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:13306/test_data?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:19000/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
    status-page-url: http://localhost:${server.port}/swagger-ui.html
user-security-filter:
  default: false
  exceptions: swagger