FROM openjdk:8-jdk-alpine
ENV APP_NAME @project.build.finalName@.@project.packaging@
ADD @project.build.finalName@.@project.packaging@ app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

EXPOSE 9101