server:
  port: 19101
spring:
  application:
    name: web-framework
  zipkin:
     base-url: http://zipkin:19004
     enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:19000/eureka/
  instance:
    preferIpAddress: true
user-security-filter:
  default: false
  exceptions: /home.html,/img/,/libs/